### ISSUE TITLE
Incorrect coloring when black takes pieces

### ISSUE THREAD

**Issue by BaxterKirikiri** [zolomohan/react-native-firebase-google-auth#1]
When black takes a white piece, the coloring appears bugged like so:

![Screenshot 2021-06-02 170944](https://user-images.githubusercontent.com/52315900/120427073-5e1f1100-c3c5-11eb-8834-39e33da1cf41.jpg)

The game is still functional with this issue so currently the severity is low. I will implement the other planned functionalities before coming back to fix this.

**Comment by zolomohan** [comment]
Hi @BaxterKirikiri. I think you've created the issue in the wrong repo 🤐

**Comment by BaxterKirikiri** [comment]
Indeed I have. Really sorry about that.
